### PR TITLE
Fixed a bug with the definition of the size of the encrypted file

### PR DESCRIPTION
**Pull request by mgrachev**

### CODE REVIEW

**Comment by ankit8898** [comment]
@mgrachev thanks for this pull.  Can you let me know about the bug ?

**Comment by mgrachev** [comment]
The problem in the method `CarrierWave:: SanitizedFile#size`
I added an additional condition in this method:

```
if exists?
  File.size(path)
elsif defined? Carrierwave::EncrypterDecrypter
  File.size(path + '.enc') rescue 0
else
  0
end
```

**Comment by mgrachev** [comment]
As well have a problem with decoding files with Cyrillic names:

---

No such file or directory - /Users/mgrachev/Development/Rails/project_name/uploads/upload/attach/65/%D0%A4%D0%B0%D0%B9%D0%BB%20%D0%B4%D0%BB%D1%8F%20%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2.png.enc

---

Сheck in the console (rails console):

```
➜ dir = '/Users/mgrachev/Development/Rails/project_name/uploads/upload/attach/65/'
=> "/Users/mgrachev/Development/Rails/project_name/uploads/upload/attach/65/"

➜ file = '%D0%A4%D0%B0%D0%B9%D0%BB%20%D0%B4%D0%BB%D1%8F%20%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2.png.enc'
=> "%D0%A4%D0%B0%D0%B9%D0%BB%20%D0%B4%D0%BB%D1%8F%20%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2.png.enc"

➜ File.exists? dir + file
=> false

➜ unescaped_file = URI.unescape(file)
=> "Файл для тестов.png.enc"

➜ File.exists? dir + unescaped_file
=> true
```

**Comment by mgrachev** [comment]
As well fixed bug with deleting an encrypted file

**Pull request closed without merging**
